cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 1 --end 21
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 22 --end 41
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 42 --end 59
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 60 --end 77
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 78 --end 95
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 96 --end 113
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 114 --end 131
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 132 --end 149
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 150 --end 167
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 168 --end 185
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 186 --end 203
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 204 --end 221
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 222 --end 239
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 240 --end 257