echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 751 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 751 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 751 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 752 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 752 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 752 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 753 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 753 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 753 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 754 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 754 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 754 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 755 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 755 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 755 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 756 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 756 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 756 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 757 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 757 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 757 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 758 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 758 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 758 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 759 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 759 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 759 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 760 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 760 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 760 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 761 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 761 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 761 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 762 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 762 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 762 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 763 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 763 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 763 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 764 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 764 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 764 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 765 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 765 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 765 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 766 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 766 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 766 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 767 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 767 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 767 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 768 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 768 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 768 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 769 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 769 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 769 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 770 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 770 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 770 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 771 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 771 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 771 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 772 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 772 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 772 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 773 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 773 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 773 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 774 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 774 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 774 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 775 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 775 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 775 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 776 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 776 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 776 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 777 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 777 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 777 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 778 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 778 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 778 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 779 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 779 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 779 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 780 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-300ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 780 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 780 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 781 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 781 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 781 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 782 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 782 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 782 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 783 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 783 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 783 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 784 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 784 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 784 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 785 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 785 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 785 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 786 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 786 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 786 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 787 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 787 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 787 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 788 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 788 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 788 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 789 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 789 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 789 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 790 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 790 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 790 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 791 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 791 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 791 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 792 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 792 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 792 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 793 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 793 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 793 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 794 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 794 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 794 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 795 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 795 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 795 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 796 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 796 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 796 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 797 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 797 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 797 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 798 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 798 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 798 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 799 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 799 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 799 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 800 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 800 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 800 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 801 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 801 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 801 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 802 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 802 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 802 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 803 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 803 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 803 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 804 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 804 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 804 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 805 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 805 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 805 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 806 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 806 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 806 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 807 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 807 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 807 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 808 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 808 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 808 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 809 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 809 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 809 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 810 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 810 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 810 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 811 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 811 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 811 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 812 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 812 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 812 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 813 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 813 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 813 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 814 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 814 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 814 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 815 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 815 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 815 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 816 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 816 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 816 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 817 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 817 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 817 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 818 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 818 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 818 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 819 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 819 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 819 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 820 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 820 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 820 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 821 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 821 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 821 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 822 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 822 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 822 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 823 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 823 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 823 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 824 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 824 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 824 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 825 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity slow-400ms --fault_start_time 50 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 825 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 825 / 1200" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-50To50-20iter.log

