version: '3.0'

services:
  etcd0:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd0
    container_name: etcd0
    command:
      - etcd
      - --name=etcd0
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd0}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always

  etcd1:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd1
    container_name: etcd1
    command:
      - etcd
      - --name=etcd1
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd1}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started

  etcd2:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd2
    container_name: etcd2
    command:
      - etcd
      - --name=etcd2
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd2:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd2}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started

  etcd3:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd3
    container_name: etcd3
    command:
      - etcd
      - --name=etcd3
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd3:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd3}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started

  etcd4:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd4
    container_name: etcd4
    command:
      - etcd
      - --name=etcd4
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd4:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd4:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd4}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started

  etcd5:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd5
    container_name: etcd5
    command:
      - etcd
      - --name=etcd5
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd5:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd5:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd5}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd4:
        condition: service_started

  etcd6:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd6
    container_name: etcd6
    command:
      - etcd
      - --name=etcd6
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd6:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd6:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd6}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd4:
        condition: service_started
      etcd5:
        condition: service_started

  etcd7:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd7
    container_name: etcd7
    command:
      - etcd
      - --name=etcd7
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd7:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd7:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd7}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd4:
        condition: service_started
      etcd5:
        condition: service_started
      etcd6:
        condition: service_started

  etcd8:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd8
    container_name: etcd8
    command:
      - etcd
      - --name=etcd8
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd8:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd8:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd8}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd4:
        condition: service_started
      etcd5:
        condition: service_started
      etcd6:
        condition: service_started
      etcd7:
        condition: service_started

  etcd9:
    image: matt12313/xinda-etcd:3.5.10 # quay.io/coreos/etcd:v3.5.0
    hostname: etcd9
    container_name: etcd9
    command:
      - etcd
      - --name=etcd9
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd9:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd9:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380,etcd6=http://etcd6:2380,etcd7=http://etcd7:2380,etcd8=http://etcd8:2380,etcd9=http://etcd9:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - ${LOCAL_DIR_etcd9}:${CONTAINER_DIR_etcd}
    networks:
      - etcd
    restart: always
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd4:
        condition: service_started
      etcd5:
        condition: service_started
      etcd6:
        condition: service_started
      etcd7:
        condition: service_started
      etcd8:
        condition: service_started


  etcd-benchmark:
    image: rmlu/etcd-benchmark:latest
    container_name: etcd-benchmark
    privileged: true
    depends_on:
      - etcd0
      - etcd1
      - etcd2
      - etcd3
      - etcd4
      - etcd5
      - etcd6
      - etcd7
      - etcd8
      - etcd9
    command: tail -f /dev/null
    networks:
      - etcd



networks:
  etcd:
    driver: bridge