version: '3.9'

services:
  # roach0 serves as bystander outside cluster
  # mainly to use its cockroach cli to access cluster members
  roach0:
    image: cockroachdb/cockroach:v23.1.11
    container_name: roach0
    hostname: roach0
    networks:
      - roachnet
    restart: always
    command: start-single-node

  roach1:
    image: rmlu/cockroach:testing
    container_name: roach1
    hostname: roach1
    user: ${UID}:${GID}
    ports:
      - "26257:26257"
      - "8079:8080"
    volumes:
      - ${LOCAL_DIR_roach1}:${CONTAINER_DIR_roach1}
    env_file:
      - .env
    networks:
      - roachnet
    command: start --advertise-addr=roach1:26357 --http-addr=roach1:8080 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEM_LIMIT}

  roach2:
    image: rmlu/cockroach:testing
    container_name: roach2
    hostname: roach2
    ports:
      - "26258:26257"
      - "8081:8080"
    networks:
      - roachnet
    command: start --advertise-addr=roach2:26357 --http-addr=roach2:8080 --listen-addr=roach2:26357 --sql-addr=roach2:26257 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    depends_on:
      roach1:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEM_LIMIT}

  roach3:
    image: rmlu/cockroach:testing
    container_name: roach3
    hostname: roach3
    ports:
      - "26259:26257"
      - "8082:8080"
    networks:
      - roachnet
    command: start --advertise-addr=roach3:26357 --http-addr=roach3:8080 --listen-addr=roach3:26357 --sql-addr=roach3:26257 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    depends_on:
      roach1:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEM_LIMIT}

networks:
  roachnet:
    driver: bridge
