version: "3"
 
services:
 
  cas1:
    image: "cassandra:4.0.10"
    container_name: "cas1"
    ports:
      - "9042:9042"
    environment:
      - "CASSANDRA_SEEDS=cas1"
    volumes:
      - ${LOCAL_DIR_cas1}:${CONTAINER_DIR_cas}
    user: ${UID}:${GID}
    env_file: .env
    cpus: ${CPU_LIMIT}
    mem_limit: ${MEM_LIMIT}

  cas2:
    image: "cassandra:4.0.10"
    container_name: "cas2"
    environment:
      - "CASSANDRA_SEEDS=cas1"
    volumes:
      - ./healthcheck.sh:/tmp/healthcheck.sh
    healthcheck:
      test: 'bash /tmp/healthcheck.sh'
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - "cas1"
    env_file: .env
    cpus: ${CPU_LIMIT}
    mem_limit: ${MEM_LIMIT}
 
  cas3:
    image: "cassandra:4.0.10"
    container_name: "cas3"
    environment:
      - "CASSANDRA_SEEDS=cas1"
    restart: on-failure
    depends_on:
      cas2:
        condition: service_healthy
    env_file: .env
    cpus: ${CPU_LIMIT}
    mem_limit: ${MEM_LIMIT}
