echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 201 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 1 --unique_identifier 201 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 201 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 202 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 2 --unique_identifier 202 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 202 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 203 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 3 --unique_identifier 203 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 203 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 204 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 4 --unique_identifier 204 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 204 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 205 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 5 --unique_identifier 205 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 205 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 206 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 6 --unique_identifier 206 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 206 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 207 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 7 --unique_identifier 207 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 207 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 208 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 8 --unique_identifier 208 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 208 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 209 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 9 --unique_identifier 209 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 209 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 210 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 10 --unique_identifier 210 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 210 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 211 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 11 --unique_identifier 211 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 211 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 212 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 12 --unique_identifier 212 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 212 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 213 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 13 --unique_identifier 213 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 213 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 214 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 14 --unique_identifier 214 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 214 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 215 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 15 --unique_identifier 215 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 215 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 216 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 16 --unique_identifier 216 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 216 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 217 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 17 --unique_identifier 217 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 217 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 218 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 18 --unique_identifier 218 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 218 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 219 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 19 --unique_identifier 219 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 219 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 220 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 20 --unique_identifier 220 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 220 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 221 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 21 --unique_identifier 221 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 221 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 222 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 22 --unique_identifier 222 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 222 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 223 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 23 --unique_identifier 223 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 223 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 224 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 24 --unique_identifier 224 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 224 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 225 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 25 --unique_identifier 225 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 225 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 226 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 26 --unique_identifier 226 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 226 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 227 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 27 --unique_identifier 227 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 227 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 228 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 28 --unique_identifier 228 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 228 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 229 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 29 --unique_identifier 229 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 229 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 230 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 30 --unique_identifier 230 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 230 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 231 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 31 --unique_identifier 231 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 231 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 232 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 32 --unique_identifier 232 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 232 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 233 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 33 --unique_identifier 233 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 233 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 234 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 34 --unique_identifier 234 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 234 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 235 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 35 --unique_identifier 235 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 235 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 236 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 36 --unique_identifier 236 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 236 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 237 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 37 --unique_identifier 237 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 237 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 238 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 38 --unique_identifier 238 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 238 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 239 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 39 --unique_identifier 239 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 239 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 240 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 40 --unique_identifier 240 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 240 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 241 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 41 --unique_identifier 241 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 241 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 242 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 42 --unique_identifier 242 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 242 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 243 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 43 --unique_identifier 243 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 243 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 244 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 44 --unique_identifier 244 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 244 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 245 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 45 --unique_identifier 245 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 245 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 246 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 46 --unique_identifier 246 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 246 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 247 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 47 --unique_identifier 247 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 247 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 248 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 48 --unique_identifier 248 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 248 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 249 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 49 --unique_identifier 249 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 249 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 250 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 50 --unique_identifier 250 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 250 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 251 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 1 --unique_identifier 251 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 251 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 252 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 2 --unique_identifier 252 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 252 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 253 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 3 --unique_identifier 253 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 253 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 254 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 4 --unique_identifier 254 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 254 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 255 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 5 --unique_identifier 255 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 255 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 256 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 6 --unique_identifier 256 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 256 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 257 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 7 --unique_identifier 257 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 257 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 258 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 8 --unique_identifier 258 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 258 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 259 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 9 --unique_identifier 259 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 259 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 260 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 10 --unique_identifier 260 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 260 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 261 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 11 --unique_identifier 261 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 261 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 262 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 12 --unique_identifier 262 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 262 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 263 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 13 --unique_identifier 263 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 263 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 264 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 14 --unique_identifier 264 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 264 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 265 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 15 --unique_identifier 265 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 265 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 266 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 16 --unique_identifier 266 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 266 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 267 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 17 --unique_identifier 267 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 267 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 268 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 18 --unique_identifier 268 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 268 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 269 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 19 --unique_identifier 269 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 269 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 270 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 20 --unique_identifier 270 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 270 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 271 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 21 --unique_identifier 271 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 271 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 272 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 22 --unique_identifier 272 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 272 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 273 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 23 --unique_identifier 273 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 273 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 274 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 24 --unique_identifier 274 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 274 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 275 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 25 --unique_identifier 275 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 275 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 276 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 26 --unique_identifier 276 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 276 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 277 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 27 --unique_identifier 277 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 277 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 278 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 28 --unique_identifier 278 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 278 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 279 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 29 --unique_identifier 279 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 279 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 280 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 30 --unique_identifier 280 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 280 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 281 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 31 --unique_identifier 281 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 281 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 282 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 32 --unique_identifier 282 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 282 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 283 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 33 --unique_identifier 283 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 283 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 284 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 34 --unique_identifier 284 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 284 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 285 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 35 --unique_identifier 285 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 285 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 286 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 36 --unique_identifier 286 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 286 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 287 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 37 --unique_identifier 287 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 287 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 288 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 38 --unique_identifier 288 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 288 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 289 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 39 --unique_identifier 289 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 289 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 290 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 40 --unique_identifier 290 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 290 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 291 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 41 --unique_identifier 291 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 291 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 292 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 42 --unique_identifier 292 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 292 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 293 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 43 --unique_identifier 293 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 293 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 294 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 44 --unique_identifier 294 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 294 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 295 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 45 --unique_identifier 295 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 295 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 296 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 46 --unique_identifier 296 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 296 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 297 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 47 --unique_identifier 297 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 297 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 298 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 48 --unique_identifier 298 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 298 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 299 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 49 --unique_identifier 299 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 299 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 300 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 40 --fault_severity flaky-p5 --fault_start_time 30 --bench_exec_time 120 --benchmark copilot --copilot_concurrency 1 --copilot_scheme copilot --iter 50 --unique_identifier 300 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 300 / 1800" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur-40-st-30To30-50iter.log

