cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 1 --wkl readonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 1 --wkl writeonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 1 --wkl mixed
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 1 --wkl readonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 1 --wkl writeonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 1 --wkl mixed
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 8 --wkl readonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 8 --wkl writeonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 8 --wkl mixed
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 8 --wkl readonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 8 --wkl writeonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 8 --wkl mixed
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 32 --wkl readonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 32 --wkl writeonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 32 --wkl mixed
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 32 --wkl readonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 32 --wkl writeonly
cd ~/workdir/hbase-pipeline/figure/workload-change; python3 different-workload.py --rc 1000000 --tc 32 --wkl mixed