cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 1 --wkl a
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 1 --wkl c
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 1 --wkl g
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 1 --wkl a
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 1 --wkl c
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 1 --wkl g
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 8 --wkl a
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 8 --wkl c
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 8 --wkl g
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 8 --wkl a
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 8 --wkl c
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 8 --wkl g
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 32 --wkl a
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 32 --wkl c
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 10000 --tc 32 --wkl g
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 32 --wkl a
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 32 --wkl c
cd ~/workdir/crdb-pipeline/figure/workload-change; python3 different-workload.py --rc 100000 --tc 32 --wkl g