version: "2"

services:
  kafka1:
    image: docker.io/bitnami/kafka:3.5
    hostname: kafka1
    container_name: kafka1
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - ${LOCAL_DIR_kafka1}:${CONTAINER_DIR}
    user: 1006:0
    env_file: .env
    environment:
      # KRaft settings
      - KAFKA_KRAFT_CLUSTER_ID=ZGI1NTk0YmY3NzVjNDk5MD
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_RETENTION_MS=5000
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=1000 # The frequency in milliseconds that the log cleaner checks whether any log is eligible for deletion
      - KAFKA_CFG_LOG_RETENTION_MS=5000 # The time to keep a log file before deleting it (in milliseconds)
      - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=5000 # time to wait before deleting a file from the filesystem
      # - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760 # 10MB, twins of KAFKA_CFG_LOG_ROLL_MS
      - KAFKA_CFG_LOG_ROLL_MS=5000 # Twins of KAFKA_CFG_LOG_SEGMENT_BYTES: The maximum time before a new log segment is rolled out (in milliseconds).
      - KAFKA_CFG_LOG_CLEANER_THREADS=8 # The number of background threads to use for log cleaning

  kafka2:
    image: docker.io/bitnami/kafka:3.5
    hostname: kafka2
    container_name: kafka2
    restart: always
    ports:
      - "9093:9092"
    environment:
      # KRaft settings
      - KAFKA_KRAFT_CLUSTER_ID=ZGI1NTk0YmY3NzVjNDk5MD
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_RETENTION_MS=5000
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=1000 # The frequency in milliseconds that the log cleaner checks whether any log is eligible for deletion
      - KAFKA_CFG_LOG_RETENTION_MS=5000 # The time to keep a log file before deleting it (in milliseconds)
      - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=5000 # time to wait before deleting a file from the filesystem
      # - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760 # 10MB, twins of KAFKA_CFG_LOG_ROLL_MS
      - KAFKA_CFG_LOG_ROLL_MS=5000 # Twins of KAFKA_CFG_LOG_SEGMENT_BYTES: The maximum time before a new log segment is rolled out (in milliseconds).
      - KAFKA_CFG_LOG_CLEANER_THREADS=8 # The number of background threads to use for log cleaning

  kafka3:
    image: docker.io/bitnami/kafka:3.5
    hostname: kafka3
    container_name: kafka3
    restart: always
    ports:
      - "9094:9092"
    environment:
      # KRaft settings
      - KAFKA_KRAFT_CLUSTER_ID=ZGI1NTk0YmY3NzVjNDk5MD
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_RETENTION_MS=5000
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=1000 # The frequency in milliseconds that the log cleaner checks whether any log is eligible for deletion
      - KAFKA_CFG_LOG_RETENTION_MS=5000 # The time to keep a log file before deleting it (in milliseconds)
      - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=5000 # time to wait before deleting a file from the filesystem
      # - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760 # 10MB, twins of KAFKA_CFG_LOG_ROLL_MS
      - KAFKA_CFG_LOG_ROLL_MS=5000 # Twins of KAFKA_CFG_LOG_SEGMENT_BYTES: The maximum time before a new log segment is rolled out (in milliseconds).
      - KAFKA_CFG_LOG_CLEANER_THREADS=8 # The number of background threads to use for log cleaning

  kafka4:
    image: docker.io/bitnami/kafka:3.5
    hostname: kafka4
    container_name: kafka4
    restart: always
    ports:
      - "9095:9092"
    environment:
      # KRaft settings
      - KAFKA_KRAFT_CLUSTER_ID=ZGI1NTk0YmY3NzVjNDk5MD
      - KAFKA_CFG_NODE_ID=4
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka4:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_RETENTION_MS=5000
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=1000 # The frequency in milliseconds that the log cleaner checks whether any log is eligible for deletion
      - KAFKA_CFG_LOG_RETENTION_MS=5000 # The time to keep a log file before deleting it (in milliseconds)
      - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=5000 # time to wait before deleting a file from the filesystem
      # - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760 # 10MB, twins of KAFKA_CFG_LOG_ROLL_MS
      - KAFKA_CFG_LOG_ROLL_MS=5000 # Twins of KAFKA_CFG_LOG_SEGMENT_BYTES: The maximum time before a new log segment is rolled out (in milliseconds).
      - KAFKA_CFG_LOG_CLEANER_THREADS=8 # The number of background threads to use for log cleaning

  kafka-benchmarking:
    image: amazoncorretto
    hostname: kafka-benchmarking
    container_name: kafka-benchmarking
    volumes:
      - /data/ruiming/xinda/xinda-software/kafka:/kafka
    # keep the container running by starting the bash shell
    command: tail -f /dev/null
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
