cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 0 --end 42
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 43 --end 84
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 85 --end 122
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 123 --end 160
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 161 --end 198
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 199 --end 236
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 237 --end 274
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 275 --end 312
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 313 --end 350
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 351 --end 388
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 389 --end 426
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 427 --end 464
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 465 --end 502
cd ~/workdir/hbase-pipeline/finetune; python3 finetune.py --start 503 --end 540