---
- name: Install Xinda only
  hosts: all

  tasks:
    - name: Get the home directory
      become: false
      command: echo $HOME
      register: home

    - name: create Xinda dir
      become: false
      ansible.builtin.file:
        path: "{{ home.stdout }}/workdir/xinda"
        state: directory

    - name: clone Xinda repo
      become: false
      ansible.builtin.git:
        dest: "{{ home.stdout }}/workdir/xinda"
        repo: git@github.com:OrderLab/xinda.git
        version: master
        accept_hostkey: yes
