- hosts: all
  vars:
      task_name: "{{ task }}"
  tasks:
    - name: Compress experiment data into a tarball
      shell: >
        tar -cf $HOME/workdir/data/default_$(hostname -i)_{{ task_name }}.tar --exclude='**/misc*' $HOME/workdir/data/default
# ansible-playbook compress_copilot_exp_data.yml -i ansible_host --extra-vars "task=copilot-nw-slow-conc"