---
- name: Install everything
  hosts: all
  vars_files:
    - data.yml

- name: Mount file systems
  import_playbook: tmpfs.yml

- name: Install docker
  import_playbook: docker.yml

- name: Install utilities available from APT-GET # Charybdefs compilation requires libfuse-dev 
  import_playbook: install_apt_utilities.yml

- name: Install xinda
  import_playbook: xinda.yml

- name: Install blockade
  import_playbook: blockade.yml

- name: Install CMake
  import_playbook: cmake.yml

- name: Install Thrift
  import_playbook: thrift.yml

- name: Install M4
  import_playbook: m4.yml

- name: Install Autoconf
  import_playbook: autoconf.yml

- name: Install Charybdefs
  import_playbook: charybdefs.yml

- name: Install Java
  import_playbook: openjdk.yml

- name: Install Maven
  import_playbook: maven.yml

- name: Compile OpenMessaging
  import_playbook: openmessaging.yml

- name: Add alias
  import_playbook: alias.yml

- name: Pre-pull all docker images
  import_playbook: docker_images.yml

