---
- name: pip3 install necessary packages
  hosts: all
  become: false

  tasks:
    - name: pip3 install
      shell: |
        conda run -n py36 pip3 install docker
        conda run -n py36 pip3 install psutil
        conda run -n py36 pip3 install gitpython
        conda run -n py36 pip3 install pyyaml
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.HOME }}/miniconda3/condabin:{{ ansible_env.PATH }}"
