- hosts: all
  vars:
    script_path: "{{ lookup('env','SCRIPT_NAME') }}"
    script_name: "{{ script_path | basename }}"
  tasks:
    - name: Copy script to server
      copy:
        src: "{{ script_path }}"
        dest: "$HOME/workdir/hbase-pipeline/finetune/{{ script_name }}"
        
    - name: Change script mode to executable
      file:
        path: "$HOME/workdir/hbase-pipeline/finetune/{{ script_name }}"
        mode: 0755

    - name: Run script inside tmux session
      shell: >
        tmux new-session -d -s finetune 'bash -c "source ~/miniconda3/bin/activate py36; $HOME/workdir/hbase-pipeline/finetune/{{ script_name }}; read"'
    
    - name: Tail meta log
      shell: >
        tmux split-window -t finetune:0 'bash -c "tail -f $HOME/workdir/hbase-pipeline/finetune/meta.log"'