---
- name: update xinda
  hosts: all
  become: false

  tasks:
    - name: check if xinda exists
      stat:
        path: $HOME/workdir/xinda
      register: xinda_exists

    - name: update xinda
      shell: |
        cd $HOME/workdir/xinda
        git pull --rebase
      args:
        executable: /bin/bash
      when: xinda_exists.stat.exists

    - name: create Xinda dir
      become: false
      ansible.builtin.file:
        path: "$HOME/workdir/xinda"
        state: directory
      when: xinda_exists.stat.exists == False

    - name: clone Xinda repo
      become: false
      ansible.builtin.git:
        dest: "$HOME/workdir/xinda"
        repo: git@github.com:OrderLab/xinda.git
        version: master
        accept_hostkey: yes
      when: xinda_exists.stat.exists == False
    
    - name: check the latest git commit id
      shell: |
        cd $HOME/workdir/xinda
        git rev-parse --short HEAD
      register: check_output

    - name: Show output of git check
      debug:
        msg: "commit ID: {{ check_output.stdout }}"