---
- name: Install Xinda
  hosts: all

  tasks:
    - name: Get the home directory
      become: false
      command: echo $HOME
      register: home

    - name: create Xinda dir
      become: false
      ansible.builtin.file:
        path: "{{ home.stdout }}/workdir/xinda"
        state: directory

    - name: clone Xinda repo
      become: false
      ansible.builtin.git:
        dest: "{{ home.stdout }}/workdir/xinda"
        repo: https://github.com/OrderLab/xinda.git
        version: master
        accept_hostkey: yes

    - name: create Xinda-Software dir
      become: false
      ansible.builtin.file:
        path: "{{ home.stdout }}/workdir/xinda-software"
        state: directory

    - name: clone Xinda-Software repo
      become: false
      ansible.builtin.git:
        dest: "{{ home.stdout }}/workdir/xinda-software"
        repo: https://github.com/OrderLab/xinda-software.git
        version: master
        accept_hostkey: yes
