echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1369 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 25 --unique_identifier 1369 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1369 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1370 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 26 --unique_identifier 1370 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1370 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1371 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 27 --unique_identifier 1371 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1371 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1372 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 28 --unique_identifier 1372 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1372 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1373 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 1373 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1373 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1374 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 1374 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1374 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1375 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 1375 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1375 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1376 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 1376 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1376 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1377 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 1377 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1377 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1378 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 1378 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1378 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1379 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 1379 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1379 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1380 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 1380 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1380 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1381 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 1381 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1381 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1382 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 1382 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1382 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1383 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 1383 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1383 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1384 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 1384 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1384 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1385 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 1385 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1385 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1386 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 1386 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1386 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1387 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 1387 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1387 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1388 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 1388 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1388 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1389 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 1389 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1389 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1390 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 1390 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1390 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1391 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 1391 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1391 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1392 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 1392 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1392 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1393 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 21 --unique_identifier 1393 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1393 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1394 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 22 --unique_identifier 1394 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1394 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1395 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 23 --unique_identifier 1395 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1395 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1396 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 24 --unique_identifier 1396 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1396 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1397 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 25 --unique_identifier 1397 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1397 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1398 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 26 --unique_identifier 1398 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1398 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1399 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 27 --unique_identifier 1399 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1399 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1400 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 28 --unique_identifier 1400 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1400 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1401 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 1401 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1401 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1402 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 1402 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1402 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1403 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 1403 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1403 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1404 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 1404 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1404 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1405 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 1405 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1405 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1406 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 1406 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1406 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1407 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 1407 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1407 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1408 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 1408 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1408 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1409 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 1409 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1409 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1410 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 1410 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1410 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1411 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 1411 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1411 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1412 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 1412 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1412 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1413 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 1413 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1413 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1414 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 1414 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1414 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1415 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 1415 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1415 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1416 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 1416 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1416 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1417 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 1417 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1417 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1418 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 1418 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1418 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1419 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 1419 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1419 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1420 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 1420 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1420 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1421 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 21 --unique_identifier 1421 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1421 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1422 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 22 --unique_identifier 1422 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1422 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1423 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 23 --unique_identifier 1423 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1423 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1424 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 24 --unique_identifier 1424 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1424 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1425 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 25 --unique_identifier 1425 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1425 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1426 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 26 --unique_identifier 1426 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1426 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1427 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 27 --unique_identifier 1427 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1427 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1428 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica3 --fault_duration 60 --fault_severity slow-300ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 28 --unique_identifier 1428 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1428 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1429 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 1429 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1429 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1430 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 1430 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1430 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1431 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 1431 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1431 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1432 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 1432 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1432 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1433 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 1433 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1433 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1434 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 1434 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1434 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1435 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 1435 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1435 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1436 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 1436 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1436 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1437 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 1437 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1437 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1438 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 1438 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1438 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1439 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 1439 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1439 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1440 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 1440 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1440 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1441 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 1441 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1441 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1442 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 1442 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1442 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1443 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 1443 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1443 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1444 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 1444 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1444 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1445 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 1445 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1445 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1446 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 1446 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1446 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1447 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 1447 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1447 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1448 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 1448 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1448 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1449 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 21 --unique_identifier 1449 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1449 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1450 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 22 --unique_identifier 1450 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1450 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1451 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 23 --unique_identifier 1451 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1451 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1452 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 24 --unique_identifier 1452 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1452 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1453 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 25 --unique_identifier 1453 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1453 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1454 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 26 --unique_identifier 1454 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1454 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1455 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 27 --unique_identifier 1455 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1455 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1456 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 28 --unique_identifier 1456 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1456 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1457 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 1 --unique_identifier 1457 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1457 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1458 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 2 --unique_identifier 1458 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1458 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1459 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 3 --unique_identifier 1459 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1459 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1460 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 4 --unique_identifier 1460 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1460 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1461 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 5 --unique_identifier 1461 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1461 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1462 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 6 --unique_identifier 1462 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1462 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1463 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 7 --unique_identifier 1463 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1463 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1464 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 8 --unique_identifier 1464 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1464 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1465 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 9 --unique_identifier 1465 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1465 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1466 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 10 --unique_identifier 1466 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1466 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1467 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 11 --unique_identifier 1467 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1467 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1468 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 12 --unique_identifier 1468 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1468 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1469 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 13 --unique_identifier 1469 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1469 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1470 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 14 --unique_identifier 1470 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1470 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1471 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 15 --unique_identifier 1471 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1471 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1472 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 16 --unique_identifier 1472 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1472 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1473 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 17 --unique_identifier 1473 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1473 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1474 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 18 --unique_identifier 1474 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1474 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1475 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 19 --unique_identifier 1475 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1475 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1476 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 20 --unique_identifier 1476 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1476 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1477 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 21 --unique_identifier 1477 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1477 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1478 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 22 --unique_identifier 1478 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1478 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1479 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 23 --unique_identifier 1479 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1479 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1480 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 24 --unique_identifier 1480 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1480 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1481 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 25 --unique_identifier 1481 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1481 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 1482 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-400ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme copilot --iter 26 --unique_identifier 1482 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 1482 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

