echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 229 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 5 --unique_identifier 229 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 229 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 230 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 6 --unique_identifier 230 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 230 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 231 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 7 --unique_identifier 231 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 231 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 232 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 8 --unique_identifier 232 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 232 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 233 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 9 --unique_identifier 233 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 233 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 234 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 10 --unique_identifier 234 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 234 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 235 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 11 --unique_identifier 235 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 235 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 236 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 12 --unique_identifier 236 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 236 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 237 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 13 --unique_identifier 237 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 237 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 238 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 14 --unique_identifier 238 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 238 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 239 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 15 --unique_identifier 239 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 239 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 240 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 16 --unique_identifier 240 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 240 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 241 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 17 --unique_identifier 241 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 241 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 242 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 18 --unique_identifier 242 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 242 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 243 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 19 --unique_identifier 243 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 243 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 244 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 20 --unique_identifier 244 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 244 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 245 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 21 --unique_identifier 245 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 245 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 246 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 22 --unique_identifier 246 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 246 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 247 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 23 --unique_identifier 247 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 247 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 248 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 24 --unique_identifier 248 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 248 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 249 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 25 --unique_identifier 249 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 249 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 250 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 26 --unique_identifier 250 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 250 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 251 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 27 --unique_identifier 251 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 251 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 252 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 28 --unique_identifier 252 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 252 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 253 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 1 --unique_identifier 253 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 253 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 254 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 2 --unique_identifier 254 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 254 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 255 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 3 --unique_identifier 255 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 255 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 256 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 4 --unique_identifier 256 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 256 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 257 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 5 --unique_identifier 257 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 257 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 258 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 6 --unique_identifier 258 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 258 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 259 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 7 --unique_identifier 259 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 259 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 260 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 8 --unique_identifier 260 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 260 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 261 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 9 --unique_identifier 261 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 261 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 262 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 10 --unique_identifier 262 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 262 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 263 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 11 --unique_identifier 263 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 263 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 264 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 12 --unique_identifier 264 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 264 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 265 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 13 --unique_identifier 265 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 265 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 266 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 14 --unique_identifier 266 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 266 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 267 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 15 --unique_identifier 267 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 267 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 268 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 16 --unique_identifier 268 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 268 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 269 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 17 --unique_identifier 269 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 269 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 270 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 18 --unique_identifier 270 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 270 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 271 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 19 --unique_identifier 271 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 271 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 272 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 20 --unique_identifier 272 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 272 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 273 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 21 --unique_identifier 273 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 273 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 274 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 22 --unique_identifier 274 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 274 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 275 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 23 --unique_identifier 275 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 275 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 276 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 24 --unique_identifier 276 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 276 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 277 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 25 --unique_identifier 277 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 277 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 278 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 26 --unique_identifier 278 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 278 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 279 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 27 --unique_identifier 279 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 279 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 280 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 28 --unique_identifier 280 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 280 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 281 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 1 --unique_identifier 281 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 281 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 282 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 2 --unique_identifier 282 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 282 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 283 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 3 --unique_identifier 283 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 283 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 284 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 4 --unique_identifier 284 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 284 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 285 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 5 --unique_identifier 285 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 285 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 286 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 6 --unique_identifier 286 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 286 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 287 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 7 --unique_identifier 287 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 287 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 288 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 8 --unique_identifier 288 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 288 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 289 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 9 --unique_identifier 289 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 289 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 290 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 10 --unique_identifier 290 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 290 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 291 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 11 --unique_identifier 291 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 291 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 292 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 12 --unique_identifier 292 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 292 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 293 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 13 --unique_identifier 293 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 293 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 294 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 14 --unique_identifier 294 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 294 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 295 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 15 --unique_identifier 295 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 295 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 296 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 16 --unique_identifier 296 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 296 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 297 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 17 --unique_identifier 297 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 297 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 298 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 18 --unique_identifier 298 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 298 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 299 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 19 --unique_identifier 299 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 299 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 300 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 20 --unique_identifier 300 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 300 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 301 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 21 --unique_identifier 301 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 301 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 302 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 22 --unique_identifier 302 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 302 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 303 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 23 --unique_identifier 303 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 303 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 304 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 24 --unique_identifier 304 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 304 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 305 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 25 --unique_identifier 305 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 305 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 306 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 26 --unique_identifier 306 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 306 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 307 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 27 --unique_identifier 307 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 307 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 308 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 28 --unique_identifier 308 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 308 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 309 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 1 --unique_identifier 309 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 309 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 310 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 2 --unique_identifier 310 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 310 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 311 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 3 --unique_identifier 311 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 311 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 312 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 4 --unique_identifier 312 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 312 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 313 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 5 --unique_identifier 313 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 313 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 314 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 6 --unique_identifier 314 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 314 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 315 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 7 --unique_identifier 315 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 315 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 316 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 8 --unique_identifier 316 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 316 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 317 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 9 --unique_identifier 317 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 317 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 318 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 10 --unique_identifier 318 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 318 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 319 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 11 --unique_identifier 319 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 319 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 320 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 12 --unique_identifier 320 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 320 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 321 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 13 --unique_identifier 321 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 321 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 322 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 14 --unique_identifier 322 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 322 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 323 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 15 --unique_identifier 323 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 323 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 324 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 16 --unique_identifier 324 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 324 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 325 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 17 --unique_identifier 325 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 325 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 326 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 18 --unique_identifier 326 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 326 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 327 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 19 --unique_identifier 327 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 327 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 328 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 20 --unique_identifier 328 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 328 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 329 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 21 --unique_identifier 329 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 329 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 330 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 22 --unique_identifier 330 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 330 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 331 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 23 --unique_identifier 331 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 331 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 332 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 24 --unique_identifier 332 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 332 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 333 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 25 --unique_identifier 333 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 333 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 334 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 26 --unique_identifier 334 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 334 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 335 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 27 --unique_identifier 335 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 335 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 336 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 28 --unique_identifier 336 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 336 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 337 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 1 --unique_identifier 337 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 337 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 338 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 2 --unique_identifier 338 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 338 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 339 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 3 --unique_identifier 339 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 339 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 340 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 4 --unique_identifier 340 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 340 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 341 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 5 --unique_identifier 341 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 341 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 342 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica2 --fault_duration 60 --fault_severity slow-200ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme multipaxos --iter 6 --unique_identifier 342 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 342 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

