echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 571 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 11 --unique_identifier 571 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 571 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 572 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 12 --unique_identifier 572 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 572 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 573 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 13 --unique_identifier 573 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 573 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 574 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 14 --unique_identifier 574 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 574 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 575 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 15 --unique_identifier 575 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 575 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 576 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 16 --unique_identifier 576 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 576 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 577 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 17 --unique_identifier 577 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 577 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 578 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 18 --unique_identifier 578 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 578 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 579 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 19 --unique_identifier 579 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 579 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 580 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 20 --unique_identifier 580 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 580 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 581 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 21 --unique_identifier 581 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 581 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 582 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 22 --unique_identifier 582 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 582 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 583 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 23 --unique_identifier 583 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 583 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 584 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 24 --unique_identifier 584 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 584 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 585 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 25 --unique_identifier 585 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 585 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 586 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 26 --unique_identifier 586 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 586 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 587 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 27 --unique_identifier 587 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 587 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 588 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100us --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 28 --unique_identifier 588 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 588 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 589 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 1 --unique_identifier 589 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 589 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 590 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 2 --unique_identifier 590 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 590 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 591 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 3 --unique_identifier 591 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 591 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 592 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 4 --unique_identifier 592 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 592 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 593 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 5 --unique_identifier 593 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 593 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 594 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 6 --unique_identifier 594 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 594 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 595 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 7 --unique_identifier 595 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 595 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 596 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 8 --unique_identifier 596 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 596 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 597 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 9 --unique_identifier 597 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 597 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 598 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 10 --unique_identifier 598 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 598 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 599 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 11 --unique_identifier 599 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 599 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 600 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 12 --unique_identifier 600 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 600 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 601 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 13 --unique_identifier 601 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 601 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 602 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 14 --unique_identifier 602 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 602 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 603 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 15 --unique_identifier 603 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 603 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 604 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 16 --unique_identifier 604 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 604 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 605 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 17 --unique_identifier 605 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 605 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 606 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 18 --unique_identifier 606 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 606 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 607 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 19 --unique_identifier 607 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 607 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 608 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 20 --unique_identifier 608 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 608 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 609 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 21 --unique_identifier 609 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 609 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 610 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 22 --unique_identifier 610 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 610 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 611 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 23 --unique_identifier 611 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 611 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 612 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 24 --unique_identifier 612 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 612 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 613 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 25 --unique_identifier 613 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 613 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 614 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 26 --unique_identifier 614 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 614 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 615 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 27 --unique_identifier 615 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 615 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 616 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-1ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 28 --unique_identifier 616 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 616 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 617 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 1 --unique_identifier 617 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 617 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 618 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 2 --unique_identifier 618 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 618 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 619 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 3 --unique_identifier 619 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 619 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 620 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 4 --unique_identifier 620 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 620 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 621 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 5 --unique_identifier 621 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 621 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 622 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 6 --unique_identifier 622 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 622 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 623 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 7 --unique_identifier 623 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 623 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 624 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 8 --unique_identifier 624 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 624 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 625 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 9 --unique_identifier 625 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 625 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 626 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 10 --unique_identifier 626 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 626 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 627 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 11 --unique_identifier 627 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 627 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 628 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 12 --unique_identifier 628 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 628 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 629 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 13 --unique_identifier 629 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 629 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 630 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 14 --unique_identifier 630 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 630 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 631 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 15 --unique_identifier 631 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 631 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 632 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 16 --unique_identifier 632 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 632 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 633 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 17 --unique_identifier 633 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 633 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 634 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 18 --unique_identifier 634 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 634 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 635 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 19 --unique_identifier 635 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 635 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 636 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 20 --unique_identifier 636 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 636 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 637 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 21 --unique_identifier 637 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 637 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 638 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 22 --unique_identifier 638 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 638 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 639 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 23 --unique_identifier 639 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 639 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 640 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 24 --unique_identifier 640 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 640 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 641 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 25 --unique_identifier 641 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 641 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 642 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 26 --unique_identifier 642 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 642 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 643 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 27 --unique_identifier 643 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 643 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 644 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-5ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 28 --unique_identifier 644 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 644 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 645 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 1 --unique_identifier 645 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 645 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 646 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 2 --unique_identifier 646 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 646 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 647 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 3 --unique_identifier 647 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 647 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 648 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 4 --unique_identifier 648 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 648 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 649 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 5 --unique_identifier 649 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 649 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 650 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 6 --unique_identifier 650 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 650 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 651 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 7 --unique_identifier 651 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 651 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 652 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 8 --unique_identifier 652 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 652 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 653 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 9 --unique_identifier 653 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 653 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 654 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 10 --unique_identifier 654 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 654 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 655 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 11 --unique_identifier 655 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 655 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 656 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 12 --unique_identifier 656 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 656 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 657 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 13 --unique_identifier 657 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 657 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 658 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 14 --unique_identifier 658 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 658 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 659 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 15 --unique_identifier 659 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 659 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 660 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 16 --unique_identifier 660 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 660 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 661 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 17 --unique_identifier 661 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 661 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 662 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 18 --unique_identifier 662 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 662 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 663 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 19 --unique_identifier 663 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 663 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 664 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 20 --unique_identifier 664 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 664 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 665 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 21 --unique_identifier 665 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 665 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 666 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 22 --unique_identifier 666 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 666 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 667 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 23 --unique_identifier 667 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 667 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 668 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 24 --unique_identifier 668 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 668 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 669 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 25 --unique_identifier 669 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 669 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 670 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 26 --unique_identifier 670 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 670 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 671 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 27 --unique_identifier 671 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 671 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 672 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-10ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 28 --unique_identifier 672 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 672 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 673 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 1 --unique_identifier 673 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 673 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 674 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 2 --unique_identifier 674 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 674 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 675 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 3 --unique_identifier 675 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 675 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 676 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 4 --unique_identifier 676 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 676 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 677 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 5 --unique_identifier 677 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 677 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 678 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 6 --unique_identifier 678 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 678 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 679 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 7 --unique_identifier 679 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 679 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 680 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 8 --unique_identifier 680 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 680 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 681 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 9 --unique_identifier 681 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 681 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 682 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 10 --unique_identifier 682 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 682 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 683 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 11 --unique_identifier 683 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 683 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), BEGIN] 684 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
python3 /users/rmlu/workdir/xinda/main.py --sys_name copilot --data_dir copilot --fault_type nw --fault_location replica1 --fault_duration 60 --fault_severity slow-100ms --fault_start_time 60 --bench_exec_time 150 --benchmark copilot --copilot_concurrency 10 --copilot_scheme epaxos --iter 12 --unique_identifier 684 --batch_test_log /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo "## [$(date +%s%N), $(date +"%Y-%m-%d %H:%M:%S %Z utc%z"), END] 684 / 1596" >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log
echo -e '\n' >> /users/rmlu/workdir/xinda/test_scripts/RQ1_1/meta-copilot-nw-dur--1-60-st-60To60-28iter.log

