cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 99
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 243
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 249
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 102
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 267
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 39
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 48
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 63
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 105
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 361
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 0
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 91
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 146
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 307
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 308
cd ~/workdir/hbase-pipeline/finetune; python3 tune_workload.py --batch 524